backend:
  name: github
  repo: abdulkadirakyildiz/netlify-json
  branch: master

media_folder: ../images
public_folder: ../images

collections:
  - label: Product Update and Add
    name: products
    folder: src/content/alldata
    create: true
    extension: json
    format: json
    slug: "{{fields.slug}}_{{year}}-{{month}}-{{day}}"
    identifier_field: slug
    fields:
      - { label: slug, name: slug, widget: string, required: true  }
      - { label: Name, name: name, widget: string, required: true  }
      - { label: Price, name: price, widget: number, required: true  }
      - { label: Description, name: description, widget: string, required: true  }
      - { label: Rating, name: rating, widget: number, required: true  }
      - { label: Currentcy, name: currency, widget: string, default: ₺ , required: true }
      - { label: Image, name: image, widget: image, required: true  }
      - { label: Categories, name: categories, widget: list }
      - { label: Related Products, name: related_products, widget: list }
